config/routes.rb
Rails.application.routes.draw do
   
    devise_for :users,path_names:{sign_in: "login", sign_out: "logout"},
                 controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :userlist
    #root 'articles#index'
     #root 'articles#image'
    root 'welcome#index'
    #get 'articles/index'
    resources :articles do
    	resources :comments	
    end
   	#get '/image' => 'articles#image'
   	#get '/userlist' =>'userlist#index'
   	#get '/k', to: 'userlists#index'
   	#root 'userlists#index'
      #match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
     #get '/users/:id',  => 'users#show', :as => :user


    
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    #can :update, Article
    can :update, Article, :user_id => user.id
  end

    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
     if user.admin?
       can :manage, :all
     #else
       #can :update, Article, :user_id => user.id
     end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many:comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 3 }
  has_attached_file :avatar,styles:{ medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  belongs_to  :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  enum role: [:user, :admin]
  #after_initialize :set_default_role, :if => :new_record?

  #def set_default_role
    #self.role ||= :user
  #end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable
  has_many :articles

  def self.from_omniauth(auth)
    #where(auth.slice(:provider, :uid)).first_or_create do |user|
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|  
      user.provider = auth.provider
      user.uid = auth.uid
      #user.email=auth.email
      #byebug
      #user.username = auth.info.nickname
    end
  end
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"],without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
end
def password_required?

  super && provider.blank?

end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception 
  def after_sign_in_path_for(user)
    '/articles/new'
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    #@article = Article.new
    @article = current_user.articles.build
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    params.permit!
    # render plain: params[:article].inspect
    @article = current_user.articles.build(article_params)
    # article = Article.new(article_params)
    if @article.save
       redirect_to @article , {:notice => 'Your Article saved Succesfully' }
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article , :notice => 'Your Article updated Succesfully'
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path, :notice => 'Your Article deleted Succesfully'
  end

  # def create
  #   @article = Article.create( article_params )
  # end



  private

  def article_params
    params.require(:article).permit(:title, :text, :avatar)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # http_basic_authenticate_with name: "falgu", password: "falgu", only: :destroy
  def create
    params.permit!
    @article = Article.find(params[:article_id])
    # article = Article.new(article_params)
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
def all
	user=User.from_omniauth(request.env["omniauth.auth"])

	if user.persisted?
		sign_in_and_redirect user, notice: "signed in"
	else
		session["devise.user_attributes"] = user.attributes
		redirect_to new_article_path
		#redirect_to new_article_path
	end
end
alias_method :google_oauth2, :all
end
 

app/controllers/userlist_controller.rb
class UserlistController < ApplicationController
	def index
		@users=User.all
	end

  def new
        @user = User.new
    end

  def show
      #@user = User.find_by_id(params[:id])
      @user = User.find(params[:id])
  end

  def edit
        @user = User.find(params[:id])
    end

  def create
    @user=User.new(secure_params)
    if @user.save
      redirect_to userlist_index_path, :notice => "User created."
      else
      redirect_to userlist_index_path, :notice => "User not created."
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(secure_params)
      redirect_to userlist_index_path, :notice => "User updated."
    else
      redirect_to userlist_index_path, :alert => "Unable to update user."
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to userlist_index_path, :notice => "User deleted."
  end

  private

  #def admin_only
    #unless current_user.admin?
      #redirect_to :back, :alert => "Access denied."
    #end
  #end

  def secure_params
    params.require(:user).permit(:email, :password, :password_confirmation,:role)
  end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/g_sessions_helper.rb
module GSessionsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/userlist_helper.rb
module UserlistHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
      
<%= form_for @article do |f| %>
   
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.label :'upload your image' %><br>
    <%=f.file_field :avatar %>
    <br>
    <br>
    <br>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
 <%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/image.html.erb
<%= image_tag "index.jpeg" %>
<h1> Sachin Tendulkar</h1>
<h2>The Great Cricketer.</h2>
<%= link_to 'back' ,  controller: 'articles' %>

app/views/articles/index.html.erb
<!--<h1>Listing articles<h1>-->
<%= image_tag "index1.jpeg" %><br>
<% if user_signed_in? %>
<% if current_user.role =='admin' %>
<%#= link_to 'Sign Up', new_user_registration_path %><br>
<%= link_to 'Users list', {:controller => :userlist, :action => :index} %>
<%end%>
<%end%>

<!---<h3S> Already have an account </h3>-->
<%#= link_to 'Log in', new_user_session_path %><br>
 <!---h1>Hello,Welcome</h1-->
 <%#= link_to 'My Blog', controller: 'articles' %>
 <br>
<%#= link_to 'New article', new_article_path %>
<%= link_to 'New article', new_user_session_path %>
<table>

  <tr>
    <th><font size="4">Title</th></font>
    <th><font size="4">Text</th></font>
    <th><font size="4">Photo</th></font>
  </tr>
 
  <% @articles.each do |article| %>

    <tr>
      <td><%= link_to article.title,article_path(article) %></td>
      <td><%= article.text %></td>
      
      <td><%= image_tag article.avatar.url(:thumb) %></td>
                
      <td><%= link_to 'Show', article_path(article) %></td>
         <% if user_signed_in? %>
         <td><% if (can? :update, article) or current_user.role =='admin' %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
       <%end%>
       <%end%>
      
    </tr>

  <% end %>

</table>



<br> 
<%#= link_to 'click here to go to an image page' , {:controller => :articles, :action => :image}%>
<%#= link_to 'click here to go to an image page',image_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong><font size="4">Picture:</font></strong>
  <br>
  <%= image_tag @article.avatar.url(:medium) %>
</p>
<p>
  <strong><font size="4">Title:</font></strong>
  <%= @article.title %>
</p>
<p>
  <strong><font size="4">Text:</font></strong>
  <%= @article.text %>
</p>
<h2><font size="4"><u>Comments</u></font></h2>   
<%= render @article.comments%>
<h2> Add commment:</h2>
<%= render 'comments/form' %>
<%= link_to 'Edit', edit_article_path(@article) %>
<br>
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
	<strong><font size="2"> Commentor:</font></strong>
    <%= comment.commenter %>
</p>
<p>
    <strong><font size="2"> Comment:</font></strong>
    <%=comment.body %>
</p>
<p>
<%= link_to 'Destroy Comment' ,[comment.article, comment],
	               method: :delete,
	               data: { confirm:  'Are you sure?' } %>

</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/g_sessions/create.html.erb
<h1>GSessions#create</h1>
<p>Find me in app/views/g_sessions/create.html.erb</p>

app/views/g_sessions/destroy.html.erb
<h1>GSessions#destroy</h1>
<p>Find me in app/views/g_sessions/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<!---%= stylesheet_link_tag "style.css" %-->
    <title>Blog</title>
    <!---body style="background-color:powderblue;"-->
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
             <%#= javascript_include_tag :defaults,"rails.validations" %>
  </head>

  <body>
    <% flash.each do |key,value| %>
    <p><font color="green"><%= value %></font></p>
    <% end %>
    <%= yield %>
  </body>
  <!---<p class="notice"><%= notice %></p>-->
  <p class="alert"><%= alert %></p>
  <% if user_signed_in? %>
  <li>
  <h4> Logged in As:</h4>
  <h4S><%=current_user.email %></h4> 
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>  
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  

  </li>
  <%end%>
  
<%#= link_to ('sign in with google', user_google_oauth2_omniauth_authorize(:google_oauth2) )%>
</html>

app/views/userlist/_formforuser.html.erb
<h2>Sign up</h2>
<%= form_for(:user, url:  userlist_path, method: 'put') do |f| %>
<p>
    <%= f.label :Email %><br>
    <%= f.email_field :email %>
</p>
 
<p>
    <%= f.label :password %><br>
    <%=f.password_field :password %>
</p>
<p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
</p>
<p>
   	<%= f.select(:role,User.roles.keys.map{|role| [role.titleize,role]}) %>
    <%= f.submit "Save user" %>
 </p>
<%end%>



  

app/views/userlist/_formforusernew.html.erb
<h2>Sign up</h2>
<%= form_for(:user, url: userlist_index_path, method: 'post') do |f| %>
<p>
    <%= f.label :Email %><br>
    <%= f.email_field :email %>
</p>
 
<p>
    <%= f.label :password %><br>
    <%=f.password_field :password %>
</p>
<p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
</p>
<p>
   	<%= f.select(:role,User.roles.keys.map{|role| [role.titleize,role]}) %>
    <%= f.submit "Save user" %>
</p>
<%end%>



  

app/views/userlist/_user.html.erb
  <%=  user.email %>

app/views/userlist/edit.html.erb
<h1>edit user</h1>
<%= render 'formforuser' %>
<%= link_to 'Back', userlist_index_path %>

app/views/userlist/index.html.erb
 <h2><%= link_to 'Create new user' ,new_userlist_path %><h2>
    <table>
      <tr>
    <th><font size="4">Email</th></font>
    <th><font size="4">Role</th></font>
      </tr>
          <% @users.each do |user| %>
          <% unless user.role == 'admin' %>
            <tr>
              <td><%=  user.email %></td>
              <td><%=  user.role %></td>
              <td><%= link_to 'Edit', edit_userlist_path(user) %></td>
              <td>
               <%= link_to "Delete user", userlist_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete%>
             </td>
      </tr>
          <%end%>
          <%end%>
    <table>
          

app/views/userlist/new.html.erb
<h1>New User</h1>
<%= render 'formforusernew' %>

<%= link_to 'Back', userlist_index_path %>

app/views/welcome/index.html.erb
<%= image_tag "welcome1.png" %>
<br>
<% if user_signed_in? %>
<% unless current_user.role =='admin' %>
<%= link_to 'Go to Article Page',controller: 'articles'%>
<%end%>
<%end%>
<% if user_signed_in? %>
<% if current_user.role =='admin' %>
<%= link_to 'Users list', {:controller => :userlist, :action => :index} %>
<%end%>
<%end%>
<li><%= link_to 'Sign Up Now', new_user_registration_path %></li>